### ISSUE TITLE
Prod Installation

### ISSUE THREAD

**Issue by flowli** [LINKIWI/wekan-api#1]
Hey there,

thanks a lot for starting this useful project.
Starting in devmode works (make serve), but when I setup apache with wsgi it gives me 403 forbidden for any URL.

My Apache virtual hosts looks as follows (host is reachable and showed apache default page before):
```
<VirtualHost *:8888>
        ServerName wekan
        DocumentRoot /opt/wekan-api
        WSGIScriptAlias / /opt/wekan-api/wekan_api.wsgi
</VirtualHost>
```

What I tried already is make www-data owner of wekan-api directory

Any other ideas?

Thanks a lot
Florian

**Comment by LINKIWI** [comment]
Hm, unfortunately I can't seem to reproduce this.

I'm guessing the 403 is coming from Apache and not the service itself. This probably means there is some wonkiness between Apache versions and configuration directives.

If you are on Apache 2.4+, could you try adding this to your vhost config?

```
<Directory /opt/wekan-api>
    Require all granted
</Directory>
```

If you're on any version before 2.4, I think you should use

```
Order deny, allow
Allow from all
```

in place of `Require all granted`.

Followed by a `sudo service apache2 reload`.

**Comment by flowli** [comment]
Thanks Kevin, that 2.4+ version worked for me :-)
